apply plugin: 'com.android.library'

android {
    namespace = "com.handmark.pulltorefresh.library"
    compileSdkVersion 21
    buildToolsVersion '25.0.0'
    defaultConfig {
        minSdkVersion 1
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}

