apply plugin: 'com.android.library'
//apply plugin: 'com.google.gms.google-services'

android {
    namespace = "com.google.maps.android"
    compileSdkVersion 34
    buildToolsVersion '26.0.0'

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 34
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services:11.0.4'

//    compile 'com.google.android.gms:play-services:+'
//    compile "com.google.android.gms:play-services:7.5.+"
//    compile("com.google.android.gms:play-services-location:7.5.+") //if u are not using location you can skip this
//    compile("com.google.android.gms:play-services-maps:7.5.+")
//    compile("com.google.android.gms:play-services-location:9.6.1") //if u are not using location you can skip this
//    compile("com.google.android.gms:play-services-maps:9.6.1")
//    compile("com.google.android.gms:play-services-gcm:9.6.1")
//    compile 'com.google.android.gms:play-services:11.0.4'
//    compile("com.google.android.gms:play-services-location:7.5.0") //if u are not using location you can skip this
//    compile("com.google.android.gms:play-services-maps:7.5.0")
//    compile("com.google.android.gms:play-services-gcm:7.5.0")

}
