plugins {
    id 'com.android.library'
}

android {
    namespace = "uk.co.senab.photoview"
    compileSdk 34

    defaultConfig {
        minSdk 10
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}
